default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

  username:
  password:

development:
  <<: *default
  database: prelaunchr_development

test:
  <<: *default
  database: prelaunchr_test

production:
  <<: *default
  database: prelaunchr_production
